plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowBundle
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:${rootProject.fabric_kotlin}"
    modImplementation "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"
    modImplementation "com.cobblemon:fabric:${rootProject.cobblemon_version}"
    modImplementation "software.bernie.geckolib:geckolib-fabric-${rootProject.geckolib_version}"
    modImplementation "curse.maven:cobblemonraiddens-1349231:${rootProject.raiddens_fabric_file}"

    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    include "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    modImplementation "com.terraformersmc:modmenu:${rootProject.modmenu_version}"

    modCompileOnlyApi "info.journeymap:journeymap-api-fabric:${rootProject.journeymap_api_version}"
    modCompileOnlyApi "xaero.map:xaeroworldmap-fabric-${rootProject.xaero_map_version}"
    modCompileOnlyApi "xaero.minimap:xaerominimap-fabric-${rootProject.xaero_minimap_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    exclude 'architectury.common.json'
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}
