architectury {
    common(rootProject.enabled_platforms.split(','))
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "com.cobblemon:mod:${rootProject.cobblemon_version}"
    modCompileOnly "dev.architectury:architectury:${rootProject.architectury_api_version}"
    modCompileOnly "curse.maven:cobblemonraiddens-1349231:${rootProject.raiddens_fabric_file}"
    modImplementation "software.bernie.geckolib:geckolib-common-$rootProject.geckolib_version"
    modCompileOnlyApi "info.journeymap:journeymap-api-fabric:${rootProject.journeymap_api_version}"
    modCompileOnlyApi "xaero.map:xaeroworldmap-fabric-${rootProject.xaero_map_version}"
    modCompileOnlyApi "xaero.minimap:xaerominimap-fabric-${rootProject.xaero_minimap_version}"
}
