modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"

[[mods]]
modId="cri"
version="${version}"
displayName="Cobblemon Raid Dens Icons"
authors="ludwici"
description="Display Cobblemon Raid Dens icons on JourneyMap and Xaero maps."
logoFile="assets/cri/icon.png"

[[mixins]]
config="cri.mixins.json"
[[mixins]]
config="cri-neoforge.mixins.json"

[[dependencies.cri]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cri]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.cri]]
modId="architectury"
type="required"
versionRange="[${architectury_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cri]]
modId="cobblemon"
type="required"
versionRange="[1.7.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.cri]]
modId="cobblemonraiddens"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
